### ISSUE TITLE
老哥 跑不起来 骗你是小狗

### ISSUE THREAD

**Issue by ruoru** [tzuser/ssr#4]
step1: npm install

2: npm run build

3 npm start => error

4 npm run server => error

**Comment by tzuser** [comment]
@ruoru  朋友确实跑不起来，不好意思给你造成了困扰。

**Comment by tzuser** [comment]
@ruoru  请更新代码, 删除node_modules。再执行npm install。就可以解决错误

**Comment by ruoru** [comment]
1. 已经可以跑通了，比心。
2. 进去是 login 页面 应该默认填充账号和密码
